name: Condor Forecast Bot

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # ✅ Install the npm package so `require('playwright')` works
      - name: Install Playwright package
        run: npm i playwright@^1.47 --no-audit --no-fund --silent

      # ✅ Install the browser + OS deps
      - name: Install Playwright (Chromium)
        run: npx playwright install --with-deps chromium

      # (Optional) quick proof that the package is installed
      - name: Verify playwright is resolvable
        run: node -e "console.log(require.resolve('playwright'))"

      - name: Run node scrape.cjs
        env:
          MAKE_WEBHOOK_URL: ${{ secrets.MAKE_WEBHOOK_URL }}
          PORTAL_URL:       ${{ secrets.PORTAL_URL }}
          TIMEZONE: America/Chicago
          SHEET_NAME: AMIL.WVPA
          PRICE_THRESHOLD: '80'
          MAX_ROWS: '48'
          ROW_SELECTOR: 'table tbody tr'
          ROW_CHECKBOX_SELECTOR: 'input[type="checkbox"]'
          DOWNLOAD_BTN_SELECTOR: 'button:has-text(\"Descargar\"), [aria-label=\"Descargar\"]'
          DEBUG_SELECTORS: '0'
        run: node scrape.cjs
