name: Condor Forecast Bot

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # No "npm ci" — not needed

      - name: Install Playwright (Chromium)
        run: npx playwright install --with-deps chromium

      - name: Run node scrape.cjs
        env:
          MAKE_WEBHOOK_URL: ${{ secrets.MAKE_WEBHOOK_URL }}  # <- set in repo secrets
          PORTAL_URL:       ${{ secrets.PORTAL_URL }}        # <- set in repo secrets

          # Optional overrides (defaults already in your script):
          TIMEZONE: America/Chicago
          SHEET_NAME: AMIL.WVPA
          PRICE_THRESHOLD: '80'
          MAX_ROWS: '48'
          ROW_SELECTOR: 'table tbody tr'
          ROW_CHECKBOX_SELECTOR: 'input[type="checkbox"]'
          DOWNLOAD_BTN_SELECTOR: 'button:has-text("Descargar"), [aria-label="Descargar"]'
          DEBUG_SELECTORS: '0'   # set to '1' to print row counts and timestamps
        run: node scrape.cjs
